version: '3'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/host-production.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./root:/var/www/html
    ports:
      - '80:80'
    depends_on:
      - php
      - mariadb
  php:
    build: ./php
    env_file: ./root/.env
    volumes:
      - ./root:/var/www/html
  mariadb:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: mariadb
      MARIADB_DATABASE: mariadb
      MARIADB_USER: mariadb
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080
    depends_on:
      - mariadb

