name: Deploy to Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Write SSH private key to file
      run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa

    - name: Deploy
      run: |
        if ssh -i ~/.ssh/id_rsa -o "BatchMode=yes" -o "StrictHostKeyChecking=no" root@207.154.241.223 'echo "SSH connection successful"'; then
          echo "SSH connection successful. Deploying..."
        else
          echo "SSH connection failed. Deployment aborted."
          exit 1
        fi
